@echo off

FOR /F "tokens=*" %%g IN ('git rev-parse HEAD') DO (SET UEVR_COMMIT_HASH=%%g)

FOR /F "tokens=*" %%t IN ('git describe --tags --always --abbrev^=0') DO (SET UEVR_TAG=%%t)
IF "%UEVR_TAG%"=="" (SET UEVR_TAG=no_tag)

FOR /F "tokens=*" %%c IN ('git describe --tags --always --long') DO (SET UEVR_TAG_LONG=%%c)

REM Count commits since the tag directly; the old dash-split broke on tags that
REM themselves contain dashes (e.g. nightly-00008-<sha>), which yielded a
REM zero-padded value that C++ then parsed as an invalid octal literal.
SET UEVR_COMMITS_PAST_TAG=0
IF NOT "%UEVR_TAG%"=="no_tag" (
FOR /F "tokens=*" %%b IN ('git rev-list --count "%UEVR_TAG%..HEAD"') DO (SET UEVR_COMMITS_PAST_TAG=%%b)
)

IF "%UEVR_COMMITS_PAST_TAG%"=="" (SET UEVR_COMMITS_PAST_TAG=0)

FOR /F "tokens=*" %%b IN ('git rev-parse --abbrev-ref HEAD') DO (SET UEVR_BRANCH=%%b)

FOR /F "tokens=*" %%n IN ('git rev-list --count HEAD') DO (SET UEVR_TOTAL_COMMITS=%%n)
IF "%UEVR_TOTAL_COMMITS%"=="" (SET UEVR_TOTAL_COMMITS=0)

FOR /F "tokens=*" %%a IN ('powershell -NoProfile -Command "Get-Date -Format yyyyMMddHHmmss"') DO (
SET datetime=%%a
)

SET year=%datetime:~0,4%
SET month=%datetime:~4,2%
SET day=%datetime:~6,2%
SET hour=%datetime:~8,2%
SET minute=%datetime:~10,2%

REM Generate into a temp file first, then only replace the real header when the
REM GIT-derived content changed. This runs as a PRE_BUILD step every build; a
REM plain rewrite gave the header a fresh timestamp each time and forced
REM Framework.cpp / PluginLoader.cpp (which #include it) to recompile on every
REM build. The BUILD_DATE / BUILD_TIME lines are excluded from the comparison
REM (they change every minute); they refresh only when a git-visible change
REM already forces a rewrite.
set HASHFILE=src\CommitHash.autogenerated
set HASHTMP=src\CommitHash.autogenerated.tmp

echo #pragma once > "%HASHTMP%"
echo #define UEVR_COMMIT_HASH "%UEVR_COMMIT_HASH%" >> "%HASHTMP%"
echo #define UEVR_TAG "%UEVR_TAG%" >> "%HASHTMP%"
echo #define UEVR_TAG_LONG "%UEVR_TAG_LONG%" >> "%HASHTMP%"
echo #define UEVR_COMMITS_PAST_TAG %UEVR_COMMITS_PAST_TAG% >> "%HASHTMP%"
echo #define UEVR_BRANCH "%UEVR_BRANCH%" >> "%HASHTMP%"
echo #define UEVR_TOTAL_COMMITS %UEVR_TOTAL_COMMITS% >> "%HASHTMP%"
echo #define UEVR_BUILD_DATE "%day%.%month%.%year%" >> "%HASHTMP%"
echo #define UEVR_BUILD_TIME "%hour%:%minute%" >> "%HASHTMP%"

if not exist "%HASHFILE%" (
    move /y "%HASHTMP%" "%HASHFILE%" >nul
    goto :hashdone
)

findstr /v /c:"UEVR_BUILD_DATE" /c:"UEVR_BUILD_TIME" "%HASHFILE%" > "%HASHFILE%.a" 2>nul
findstr /v /c:"UEVR_BUILD_DATE" /c:"UEVR_BUILD_TIME" "%HASHTMP%" > "%HASHFILE%.b" 2>nul
fc "%HASHFILE%.a" "%HASHFILE%.b" >nul 2>&1
if errorlevel 1 (
    move /y "%HASHTMP%" "%HASHFILE%" >nul
) else (
    del "%HASHTMP%" >nul 2>&1
)
del "%HASHFILE%.a" "%HASHFILE%.b" >nul 2>&1

:hashdone
