param(
    [string]$GeneratorPath = (Join-Path $PSScriptRoot '..\MakeCommitHash.bat')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$generator = (Resolve-Path -LiteralPath $GeneratorPath).ProviderPath
$tempRoot = [IO.Path]::GetFullPath([IO.Path]::GetTempPath())
$tempRepo = Join-Path $tempRoot ('UEVR Build Metadata ' + [Guid]::NewGuid().ToString('N'))
$savedEnvironment = @{}
$locationPushed = $false

function Invoke-TestGit {
    $output = & git -C $tempRepo @args 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "git $($args -join ' ') failed: $($output -join '`n')"
    }
    return ($output -join "`n").Trim()
}

function Assert-Metadata {
    param([string]$Case, [long]$ExpectedCount, [string]$ExpectedTag, [string]$ExpectedTagLong = $ExpectedTag)
    $output = & $env:ComSpec /d /c MakeCommitHash.bat 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "${Case}: metadata generator failed: $($output -join '`n')"
    }
    $header = Get-Content -LiteralPath (Join-Path $tempRepo 'src\CommitHash.autogenerated') -Raw
    $count = [regex]::Match($header, '(?m)^#define UEVR_COMMITS_PAST_TAG[ \t]+([^\r\n]*)').Groups[1].Value.Trim()
    if ($count -notmatch '^(0|[1-9][0-9]*)$' -or [long]$count -ne $ExpectedCount) {
        throw "${Case}: expected decimal count $ExpectedCount, got '$count'"
    }
    $expectedNames = @{UEVR_TAG = $ExpectedTag; UEVR_TAG_LONG = $ExpectedTagLong}
    foreach ($name in $expectedNames.Keys) {
        $value = [regex]::Match($header, ('(?m)^#define ' + $name + '[ \t]+([^\r\n]*)')).Groups[1].Value.Trim()
        if ($value -cne ('"' + $expectedNames[$name] + '"')) {
            throw "${Case}: $name should preserve '$($expectedNames[$name])', got '$value'"
        }
    }
    Write-Output "PASS ${Case}: $ExpectedTag + $count"
}

try {
    # Keep the fixture independent of a parent worktree or inherited build metadata.
    $environmentNames = @('UEVR_TAG', 'UEVR_TAG_LONG', 'UEVR_COMMITS_PAST_TAG') +
        @(Get-ChildItem Env:GIT_* | Select-Object -ExpandProperty Name)
    foreach ($name in $environmentNames) {
        $savedEnvironment[$name] = [Environment]::GetEnvironmentVariable($name, 'Process')
        [Environment]::SetEnvironmentVariable($name, $null, 'Process')
    }

    New-Item -ItemType Directory -Path $tempRepo | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $tempRepo 'src'), (Join-Path $tempRepo 'empty-hooks') | Out-Null
    Copy-Item -LiteralPath $generator -Destination (Join-Path $tempRepo 'MakeCommitHash.bat')
    Invoke-TestGit -c init.templateDir= init --quiet --initial-branch=main | Out-Null
    Invoke-TestGit config user.name 'UEVR Metadata Tests' | Out-Null
    Invoke-TestGit config user.email 'metadata-tests@example.invalid' | Out-Null
    Invoke-TestGit config commit.gpgSign false | Out-Null
    Invoke-TestGit config tag.gpgSign false | Out-Null
    Invoke-TestGit config core.hooksPath (Join-Path $tempRepo 'empty-hooks') | Out-Null
    Invoke-TestGit config core.autocrlf false | Out-Null
    Invoke-TestGit commit --quiet --allow-empty -m initial | Out-Null
    Push-Location -LiteralPath $tempRepo
    $locationPushed = $true

    Assert-Metadata 'untagged checkout' 0 (Invoke-TestGit describe --tags --always --abbrev=0) (Invoke-TestGit rev-parse --short HEAD)
    Invoke-TestGit config core.abbrev 12 | Out-Null
    Assert-Metadata 'untagged checkout with custom abbreviation' 0 (Invoke-TestGit describe --tags --always --abbrev=0) (Invoke-TestGit rev-parse --short HEAD)
    Invoke-TestGit config --unset core.abbrev | Out-Null

    Invoke-TestGit tag HI-FI-RUSH-UPDATED | Out-Null
    Assert-Metadata 'exact hyphenated lightweight tag' 0 'HI-FI-RUSH-UPDATED'
    Invoke-TestGit branch side | Out-Null
    Invoke-TestGit commit --quiet --allow-empty -m main-change | Out-Null
    Assert-Metadata 'commit after hyphenated tag' 1 'HI-FI-RUSH-UPDATED'

    Invoke-TestGit switch --quiet side | Out-Null
    Invoke-TestGit commit --quiet --allow-empty -m side-change | Out-Null
    Invoke-TestGit switch --quiet main | Out-Null
    Invoke-TestGit merge --quiet --no-ff side -m merge-side | Out-Null
    Assert-Metadata 'merged history after tag' 3 'HI-FI-RUSH-UPDATED'

    Invoke-TestGit tag -a release-with-many-hyphens -m annotated | Out-Null
    Assert-Metadata 'exact annotated hyphenated tag' 0 'release-with-many-hyphens'
    Invoke-TestGit commit --quiet --allow-empty -m after-annotated | Out-Null
    Assert-Metadata 'commit after annotated tag' 1 'release-with-many-hyphens'

    Invoke-TestGit tag plain | Out-Null
    Assert-Metadata 'exact plain tag preserves metadata' 0 'plain'
    Invoke-TestGit commit --quiet --allow-empty -m after-plain | Out-Null
    Assert-Metadata 'commit after plain tag' 1 'plain'

    Invoke-TestGit tag 2026-09-11-release | Out-Null
    $env:UEVR_TAG = 'stale-tag'
    $env:UEVR_TAG_LONG = 'stale-tag'
    $env:UEVR_COMMITS_PAST_TAG = 'FI'
    Assert-Metadata 'numeric hyphenated tag with inherited metadata' 0 '2026-09-11-release'
} finally {
    if ($locationPushed) { Pop-Location }
    foreach ($name in $savedEnvironment.Keys) {
        [Environment]::SetEnvironmentVariable($name, $savedEnvironment[$name], 'Process')
    }
    if (Test-Path -LiteralPath $tempRepo) {
        $resolved = (Resolve-Path -LiteralPath $tempRepo).ProviderPath
        $expected = [IO.Path]::GetFullPath($tempRepo)
        $parent = $tempRoot.TrimEnd('\') + '\'
        if (-not $resolved.Equals($expected, [StringComparison]::OrdinalIgnoreCase) -or
            -not $resolved.StartsWith($parent, [StringComparison]::OrdinalIgnoreCase) -or
            ((Get-Item -LiteralPath $resolved).Attributes -band [IO.FileAttributes]::ReparsePoint)) {
            throw "Refusing to remove an unexpected fixture directory: $resolved"
        }
        Remove-Item -LiteralPath $resolved -Recurse -Force
    }
}
