#include "BuildIdentity.hpp"
#include "SupportDiagnostics.hpp"
#include "CommitHash.autogenerated"

namespace utility::support {
nlohmann::json current_build_identity() {
    return build_identity(UEVR_COMMIT_HASH, UEVR_UESDK_COMMIT_HASH,
        UEVR_TRACKED_DIRTY, UEVR_UESDK_TRACKED_DIRTY, UEVR_BRANCH,
        UEVR_BUILD_DATE, UEVR_BUILD_TIME);
}
}
